### ISSUE TITLE
Can monophyletic taxa in the tree be used as groups for differential testing?

### ISSUE THREAD

**Issue by Jigyasa3** [skembel/picante#19]
Hey! 

I was wondering if I want to examine if there is a difference in phylogenetic diversity of traits among monophyletic groups within the phylogenetic tree, would it make sense to use these groups as independent categories and measure significant association by Kuskal-Wallis t-test (I have 5 monophyletic groups)?

For example,
1. MNTD or MPD-
phy.dist<-cophenetic(phy)
comm.sesmpd<-ses.mpd(comm,phy.dist)

kruskal.test(comm.sesmpd$mpd.obs.z ~ as.factor(phy$clades)) #phy$clades will be stored as a column in a dataframe

**Comment by skembel** [comment]
Sorry for the slow reply to this question. It is possible to compare diversity (phylogenetic, trait) among diffrerent clades but since I would expect these values to differ as a function of diversification rate and clade age, I am not sure how informative this comparison would be. Depending on the specific question being asked it might be better to look at whether rates of diversification have shifted across the tree?
