### ISSUE TITLE
rarefaction and PD?

### ISSUE THREAD

**Issue by marwa38** [skembel/picante#28]
Hello 

Could you please advise if rarefaction affects the PD (Phylogentic diversity) or not? have you come across that? why yes or no?

Thanks

**Comment by skembel** [comment]
Hi,
rarefaction does affect PD, and samples should always be rarefied to the same number of sequences per sample if you wish to compare PD among samples. Otherwise, differences among samples in terms of PD could simply be due to the fact that one sample has more sequences than another.
So I would always strongly recommend that you rarefy your data before calculating measures of alpha diversity including richness, diversity, and phylogenetic metrics such as PD if you are working with sequencing-based data where variation among samples is due to random variation in library size rather than true differences in the abundance of organisms among samples. Otherwise, the differences you find among samples could simply be due to variation in sequencing depth rather than any biological meaningful differences in diversity among the samples.

**Comment by marwa38** [comment]
Thanks very much Steven @skembel 
I would appreciate it if you let me know if you think if rooting or unrooting the tree have any effect on PD?
I am getting this error 
```
Warning messages:
  1: In pd(ps.prev.rare.asvtab, ps.prev.rare.tree, include.root = FALSE) :
  Rooted tree and include.root=TRUE argument required to calculate PD of single-species communities. Single species community assigned PD value of NA.
2: In pd(ps.prev.rare.asvtab, ps.prev.rare.tree, include.root = FALSE) :
  Rooted tree and include.root=TRUE argument required to calculate PD of single-species communities. Single species community assigned PD value of NA.

```
