### ISSUE TITLE
abundance weighted MPD error

### ISSUE THREAD

**Issue by leorjorge** [skembel/picante#4]
There is an error in the abundance weighted MPD calculation, caused by the fact that in the current implementation, distances of the individuals and themselves are also included (the diagonal in the distance matrix). I have implemented a correction for an ongoing project, and can fork it and add a pull request. Additionally, I would like to question why mpd gives NA when there is only one species, if 0 could be meaningfull in this case. Especially given 0 distances are included in the abundance weighted case.
#5 Edit:added the pull request

**Comment by skembel** [comment]
Hi, sorry for the very long delay in responding to this. Different methods may include or exclude intra-specific phylogenetic distances when calculating MPD, so this is less an error than a choice since the methods the code were based on (e.g. Webb et al's NRI/NTI) do count intra-specific distances when calculating MPD., However, I know some methods exclude these distances when calculating MPD, so thanks for the pull request - I will incorporate this as an option to include or exclude intra-species distances when calculating MPD.
mpd returning NA when there is only one species is indeed an error and will be corrected.

**Comment by leorjorge** [comment]
Actually, my pull request is not intended to remove intraspecific distances (which I agree is a useful option) but instead to remove distances between the individual and itself. This set of distances does not make much sense in my opinion, and gives some non intuitive results.
